### ISSUE TITLE
Missing printf specifiers in grammar

### ISSUE THREAD

**Issue by lilibyte** [tree-sitter/tree-sitter-c#113]
`printf` specifiers should be their own grammar type as a child of the string literal grammar.

For example, Vim has a `cFormat` highlight group that can be changed independently of `cString`.

**Comment by lilibyte** [comment]
I think something like this would work

    string_literal: $ => seq(
      choice('L"', 'u"', 'U"', 'u8"', '"'),
      repeat(choice(
        token.immediate(prec(1, /[^\\"\n]+/)),
        $.escape_sequence,
        $.type_specifier  // new 
      )),
      '"',
    ),

    // snip

    type_specifier: $ => token(prec(1, seq(
      '%',
      choice(
        /[csdioxXfFeEaAgGnp%]/,
        /l[cs]/,
        /(hh?|ll?|j|z|t)[dioxXn]/,
        /(l|L)[fFeEaAgG]/
      )
    ))),

A table of valid type specifiers can be found [here](https://en.cppreference.com/w/c/io/fprintf). This is untested beyond checking the regexes in `node` but if the issue becomes stale I'll just figure it out and open a PR.

**Comment by maxbrunsfeld** [comment]
I don't think this should be done for every string literal. The specifier format isn't a property of string literals as a whole in C. It's just a convention used by the printf family of functions in libc.

I think it'd be better to do this using language injection, or some mechanism that can layer  additional syntax highlighting on top of the C syntax tree.

**Comment by alemuller** [comment]
> I think it'd be better to do this using language injection, or some mechanism that can layer additional syntax highlighting on top of the C syntax tree.

I go further. I think the the languague should't even try to match escape sequences. This often leads to unrecoverable error in common cases. All the literal parsing should be done elsewhere (or with some future extension to tree-sitter).

I've found that defining strings literals with the code bellow lets tree-sitter recover well from error.
```js
string_literal: $ => choice(
  token(seq(/"([^"\\\n]|\\.)*"/)), // 1
  token(seq(/"([^"\\\n]|\\.)*/),token.immediate('"')), // 2
),
```

The choice (2) is never actually matched (because the how the precedence works in tree-sitter). But it lets tree-sitter knows a quotation mark (") is expected and produce the message: `MISSING "` when the user only typed `"`. It also matches empty string.

@lilibyte The actual syntax is more complex than that.

And the standart also defines a format string for `strtime()`. So it gets messy having a single rule for all conversion specifiers.
