### ISSUE TITLE
ERROR when compiling standard include files

### ISSUE THREAD

**Issue by genotrance** [tree-sitter/tree-sitter-c#12]
Just ran stdio.h, math.h through tree-sitter and ran into ERROR. Might be worth testing with these files to verify parsing accuracy.

**Comment by maxbrunsfeld** [comment]
On macOS at least, it looks like it's because of [this](https://github.com/tree-sitter/tree-sitter-c/issues/12) preprocessor macro:

```c
#define	__BEGIN_DECLS	extern "C" {
#define	__END_DECLS	}
```

Example usage in math.h:

```c
#include <sys/cdefs.h>
#include <Availability.h>

__BEGIN_DECLS

```

Because of how open-ended the C preprocessor is, we have a limited ability to model it. The current approach is to incorporate "common" preprocessor patterns into the grammar itself so that hopefully 99% of code will parse successfully, and rely on error recovery for the remaining 1%.

For now, I think the type of error we're seeing here falls into that 1%. All of these files, for example, render very well in Atom (at least as far as I've seen) - much better than in other text editors.

Do you have thoughts on how we could handle that construct without introducing ambiguities? Or are there other specific parse errors that you're seeing in the C stdlib?

**Comment by genotrance** [comment]
There's all sorts of things failing but it seems most of these lib files have C++ code within so reporting issues against the C grammar isn't warranted. I'll open more specific issues where appropriate going forward. This one is too open ended and admittedly hard to resolve.
